plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - https://gorakhjoshi.github.io/WebDevelopmentFoundation/1.%20Modern%20Semantic%20HTML%20Markup%20/README.md
